# Generated by Django 4.2.7 on 2023-11-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yemek_tarifleri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('TR', 'Traditional'), ('IN', 'International'), ('SP', 'Special')], default='TR', max_length=2),
        ),
    ]
