# Generated by Django 4.2.7 on 2023-11-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yemek_tarifleri', '0002_remove_recipe_categories_recipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('KSK', 'Kaşık'), ('BRD', 'Bardak'), ('KG', 'Kilogram'), ('GR', 'Gram'), ('TM', 'Tutam'), ('AVC', 'Avuç'), ('GZK', 'Göz Kararı'), ('ADT', 'Adet'), ('YDM', 'Yudum')], max_length=3)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='yemek_tarifleri.recipe')),
            ],
        ),
    ]
