# Generated by Django 3.2.16 on 2023-12-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yemek_tarifleri', '0003_remove_recipe_ingredients_recipe_is_chef_recommended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('YKSK', 'Yemek Kaşığı'), ('CKSK', 'Çay Kaşığı'), ('BRD', 'Bardak'), ('KG', 'Kilogram'), ('GR', 'Gram'), ('TM', 'Tutam'), ('AVC', 'Avuç'), ('GZK', 'Göz Kararı'), ('ADT', 'Adet'), ('YDM', 'Yudum'), ('KP', 'Kepçe')], max_length=4),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('MAIN', 'Ana Yemekler'), ('APP', 'Aperatifler'), ('DES', 'Tatlılar'), ('VEGAN', 'Vegan'), ('VEG', 'Vejetaryen'), ('SEA', 'Deniz Ürünleri'), ('SOUP', 'Çorbalar'), ('SALAD', 'Salatalar'), ('QUICK', 'Hızlı ve Kolay'), ('HEALTHY', 'Sağlıklı Tarifler'), ('SP', 'Special')], default='TR', max_length=200),
        ),
    ]
